version: "3.7"

networks:
  my_network:
    driver: bridge
    
   
services:
  db_postgre:
    image: postgres:13.11
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network


  db_postgre_test:
    image: postgres:13.11
    container_name: db_postgre_test
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - ${T_POSTGRES_PORT}:5432
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  fastapi:
    build:
      context: /.   # путь к Dockerfile
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db_postgre
    networks:
      - my_network    
    
  nginx:
    image: nginx:1.24
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    environment:
      - NGINX_PORT=80
    networks:
      - my_network


volumes:
  postgres_data:
  postgres_data_test:
  
#- ${DATABASE_PORT_EXTERNAL}:${DATABASE_PORT}