version: "3.7"

networks:
  my_network:
    driver: bridge
    
   
services:
  db_postgre:
    image: postgres:13.11
    container_name: db_postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    
    
  nginx:
    image: nginx:1.24
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    environment:
      - NGINX_PORT=80
    networks:
      - my_network


volumes:
  postgres_data:
  
#- ${DATABASE_PORT_EXTERNAL}:${DATABASE_PORT}